pipeline {
     agent any
	environment {
    TIME = sh(script: 'date "+%Y-%m-%d %H:%M:%S"', returnStdout: true).trim()
      }
    stages {
      
        stage('get app') {
            steps {
                sh "wget https://raw.githubusercontent.com/eldadmozes/Project1/main/dev-tools/slim-app.py"
            }
        }

        stage('run app'){
            steps{
                sh "python3 slim-app.py"
            }
         }
     }    
}